# Generated by Django 3.1.7 on 2021-03-20 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=100)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateField(default=datetime.datetime(2021, 3, 20, 6, 4, 23, 970768, tzinfo=utc))),
                ('num_pages', models.IntegerField(default=300)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=100)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateField(default=datetime.datetime(2021, 3, 20, 6, 4, 23, 970768, tzinfo=utc))),
                ('type', models.CharField(max_length=50)),
                ('publisher', models.CharField(choices=[('BT', 'Bullet'), ('FT', 'Foot'), ('TL', 'Travel'), ('ST', 'Sport')], default='ST', max_length=50)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
    ]
