# Generated by Django 3.1.7 on 2021-03-20 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
