# Generated by Django 3.1.7 on 2021-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210320_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('BT', 'Bullet'), ('FT', 'Foot'), ('TL', 'Travel'), ('ST', 'Sport')], default='ST', max_length=50),
        ),
    ]
